## Numpy ##
1. NumPy is a Python library used for working with arrays

2. It also has functions for working in domain of linear algebra and matrices.

3. NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

4. NumPy stands for Numerical Python

## Why Use NumPy? ##

- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide **an array object that is up to 50x faster** than traditional Python lists.

- **The array object in NumPy is called ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.3'

**The array object in Numpy is called ndarray**

We can create a NumPy **ndarray** object using the  **array()** function.

## Dimensions in Arrays
1. A dimension in arrays is **one level of array depth**(nested arrays)
2. dimensions refer to the **number of axes or directions along which data is organized** in an array.
3. nested array: are arrays that have arrays as their elements.

This creates the array we can see on the right here:

![](http://jalammar.github.io/images/numpy/create-numpy-array-1.png)

In [11]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [13]:
type(array1)

numpy.ndarray

**To create a `numpy` array with more dimensions, we can pass nested lists, like this:**

![](http://jalammar.github.io/images/numpy/numpy-array-create-2d.png)

In [16]:
''' An array that has 1-D arrays as its elements is called 2-D Array'''
array2=np.array([[1,2],
                 [3,4]])
array2

array([[1, 2],
       [3, 4]])

To create a `numpy` array with more dimensions, we can pass nested lists, like this:

![](http://jalammar.github.io/images/numpy/numpy-3d-array.png)

In [3]:
array3d=np.array([[
                    [1,2],
                    [3,4]
                    ],
                  [
                      [5,6],
                      [7,8]
                  ]
                 ])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
array3dex=np.array(
                    [
                        [
                        [1,2],
                        [3,4]
                    ],
                        [
                        [5,6],
                        [7,8]
                    ]
                    ]

)
array3dex

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [5]:
array3d.shape

(2, 2, 2)

In [7]:
''' An array that has 2-D arrays(matrices) as its elements 
is called 3d array'''
array3ex=np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[10,11,12],
                    [13,14,15],
                    [16,17,18]]
                  ])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
array3ex.shape

(2, 3, 3)

In [ ]:
array4d=np.array([[
    [
        [1,2],
        [3,4],
        [5,6]
    ],
    [
        [],
        [],
        []
    ],
    [[],
    [],
    []
    ]
],[
    [],
    [],
    []
]])

In [3]:
''' A 4D array has 4 dimensions:(a,b,c,d)'''
'''That means:

2 blocks (a)

each block has 3 matrices (b)

each matrix has 3 rows (c)

each row has 2 elements (d)

So → (a, b, c, d) = (2, 3, 3, 2)'''



array4d=np.array([
                    [
                        [
                            [1,2],
                            [3,4],
                            [5,6]
                        ],
                        [
                            [7,8],
                            [9,10],
                            [11,12]
                        ],
                        [
                            [13,14],
                            [15,16],
                            [17,18]
                        ]
                    ],
                    [
                        [
                            [19,20],
                            [21,22],
                            [23,24]
                        ],
                        [
                            [25,26],
                            [27,28],
                            [29,30]
                        ],
                        [
                            [31,32],
                            [33,34],
                            [35,36]
                        ]
                    ]
])
array4d


array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [4]:
array4d.shape

(2, 3, 3, 2)

In [32]:
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

**To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:**

In [1]:
import numpy as np

In [5]:
arrayex5=np.array((12,13,14))
arrayex5

array([12, 13, 14])

In [6]:
arrayex5.shape

(3,)

###  Standard Deviation Formula

The **Standard Deviation (σ)** measures how spread out the values are from the mean.

$$
\sigma = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n}}
$$

- $x_i$: each data point  
- $\bar{x}$: mean (average)  
- $n$: number of data points  
- $\sigma$: standard deviation



If the data is only a **sample** (not the whole population), use **sample standard deviation**:
$$
s = \sqrt{\frac{\sum_{i=1}^{n} (x_i - \bar{x})^2}{n - 1}}
$$

In [3]:
#lab program
import numpy as np
# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])
# Calculate mean, standard deviation, max, and min
mean_val = np.mean(arr)
#It tells you how consistent or scattered your data is.
std_dev = np.std(arr)
max_val = np.max(arr)
min_val = np.min(arr)

# Display results of mean,std deviation,max,min
print("Array:", arr)
print("Mean:", mean_val)
print(f"Standard Deviation: {std_dev:.2f}")
print("Maximum:", max_val)
print("Minimum:", min_val)

Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.14
Maximum: 50
Minimum: 10


In [7]:
#lab program
import numpy as np

# Create two 2D arrays using np.array()
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.dot(A, B)

# Display results of matrix multiplication
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication (A x B):\n", C)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication (A x B):
 [[19 22]
 [43 50]]


## ndim attribute
- ndim attribute returns an integer that tells how many dimensions the array has

In [4]:
array1=np.array([1,2,3,4,5])
array1

array([1, 2, 3, 4, 5])

In [5]:
print(array1.ndim)

1


In [8]:
print(A.ndim)

2


In [43]:
print(array3d.ndim)

3


In [45]:
print(array3ex.ndim)

3


In [47]:
print(array4d.ndim)

4


In [50]:
print(arrayex5.ndim)

1


## ndmin argument
- defines the number of dimensions

In [52]:
array6=np.array([1,2,3,4,5], ndmin=2)

In [54]:
array6

array([[1, 2, 3, 4, 5]])

In [56]:
print(array6.ndim)

2


## shape attribute
- tells the number of elements in each dimension

In [59]:
array6.shape

(1, 5)

In [10]:
arrex=np.array([1,2,3,4,5])
arrex

array([1, 2, 3, 4, 5])

In [11]:
arrex.shape

(5,)

In [9]:
A.shape

(2, 2)

In [61]:
array1.shape

(3,)

In [63]:
array2.shape

(2, 2)

In [65]:
array3d.shape

(2, 2, 2)

In [67]:
array3ex.shape

(2, 3, 3)

In [69]:
array4d.shape

(2, 3, 3, 2)

- first dimension(2) there are 2 elements along this  axis.(outer group having 2 sub arrays)
- each of the 2 elements from the first dimension contains 3 sub arrays
- each of these 3 sub arrays from the second dimension contains 3 more elements 
- each of the 3 elements from the third dimension contains 2 elements.

In [73]:
arrayex5.shape

(3,)

## Access Array Elements
- array indexing is the same as accessing an array element
- the indexes in NumPy arrays start with 0, meaning that the first element has index0, and the second has the index 1 etc

In [80]:
array2

array([[1, 2],
       [3, 4]])

In [14]:
print(A[0][1])

2


In [13]:
A

array([[1, 2],
       [3, 4]])

In [88]:
array7=np.array([[1,2],[3.3,4]])

In [90]:
array7

array([[1. , 2. ],
       [3.3, 4. ]])

**The array will be promoted to float64 because 3.3 is a float, and making the whole array an integer would cause a loss of information.**

a numpy array can contain strings or characters but it handles them differently

In [98]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

**array(['a', 'b', 'c'], dtype='<U1') U stands for unicode string (universal character encoding system) of 1 character per string**

In [107]:
ch_arr2=np.array(["Supervised","unSupervised",
                  "sEMi-supervised","reinforcment"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcment'],
      dtype='<U15')

In [109]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcment'],
      dtype='<U15')

## dtype
- returns the data type of the array 

In [112]:
array1.dtype

dtype('int32')

In [114]:
array3d.dtype

dtype('int32')

In [116]:
array7.dtype

dtype('float64')

In [118]:
char_arr.dtype

dtype('<U1')

In [120]:
low_arr.dtype

dtype('<U15')

***dtype='S': This specifies that the data type of the array elements is a byte string. The default byte length is 1, meaning each integer is converted into its byte representation.***

In [124]:
array8=np.array([1,2,3,4,5],dtype='S')

In [126]:
array8

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [128]:
array2

array([[1, 2],
       [3, 4]])

## astype()
- Changes data type from int to float by using 'f' as parameter value:

In [130]:
array2conv=array2.astype('f')
array2conv

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [132]:
array7conv=array7.astype('i')
array7conv

array([[1, 2],
       [3, 4]], dtype=int32)

In [136]:
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [134]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

**Python numpy.ones() function returns a new array of given shape and data type, where the element’s value is set to 1.**

There are often cases when we want numpy to initialize the values of the array for us. numpy provides methods like `ones()`, `zeros()`, and `random.random()` for these cases. We just pass them the number of elements we want it to generate:

![](http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png)

In [140]:
numone=np.ones((2,2),dtype=int)
numone

array([[1, 1],
       [1, 1]])

In [142]:
numsone=np.ones((3,2))
numsone

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [144]:
numzero=np.zeros((3,2))

In [146]:
numzero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [148]:
numzeros=np.zeros((3,2),dtype=int)
numzeros

array([[0, 0],
       [0, 0],
       [0, 0]])

We can also use these methods to produce multi-dimensional arrays, as long as we pass them a tuple describing the dimensions of the matrix we want to create:

![](http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png)

![](http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png)

In [153]:
dimones=np.ones((4,3,2))

In [157]:
dimones.ndim

3

## Operations

In [179]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[5,6,7],[8,9,10]])
#addition
addition=ar1+ar2
print("addition:\n",addition)


addition:
 [[ 6  8 10]
 [12 14 16]]


In [164]:
subtraction=ar1-ar2
print("subtraction:\n",subtraction)


subtraction:
 [[-4 -4 -4]
 [-4 -4 -4]]


In [166]:
multiplication=ar1*ar2
print("multiplication:\n",multiplication)


multiplication:
 [[ 5 12 21]
 [32 45 60]]


In [168]:
division=ar1/ar2
print("division:\n", division)


division:
 [[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]


In [170]:
power=np.power(ar1,ar2)
print("power:\n",power)

power:
 [[       1       64     2187]
 [   65536  1953125 60466176]]


## broadcasting
- Broadcasting is a powerful feature that allows NumPy to work with arrays of different shapes during arithmetic operations.


In [175]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])

#add 1d array to 2d array
result=array2d + array1d
result

array([[11, 22, 25],
       [14, 25, 28]])

The 1D array [10, 20, 22] is broadcast to match the shape of the 2D array. It is treated as if it were repeated for each row of the 2D array, allowing element-wise addition.

In [187]:
array2d=np.array([[1,2,3],[4,5,6]])
array1d=np.array([10,20,22])

#add 1d array to 2d array
result=array1d + array2d
result

array([[11, 22, 25],
       [14, 25, 28]])

If the shapes of the two arrays differ in the number of dimensions, NumPy pads the smaller shape with 1 on the left until the number of dimensions match.

array1d
(3,) → Pad with a leading 1 → Shape becomes 
array1d
(1,3)
array2d
(2,3)
Now the aligned shapes are:

array1d
(1,3)
array2d
(2,3)

In [193]:
array1d.shape

(3,)

In [195]:
array2d.shape

(2, 3)

**Syntax**

import numpy as np

**np.arange(start, stop, step, dtype=None)**

**Arguments**

1.start: The starting value of the sequence (inclusive). If omitted, it defaults to 0.

2.stop: The end value of the sequence (exclusive).

3.step: The spacing between values in the sequence (default is 1). It can be positive or negative.

4.dtype: Optional data type for the elements of the array (default is float).

In [199]:
range_array=np.arange(0,10,3)
range_array

array([0, 3, 6, 9])

**np.random.randint(low, high=None, size=None, dtype=int)**

1.low: int or array-like of ints: Lowest integers are drawn from the random values.

2.high: int or array-like of ints, optional: Larger or highest integers are drawn from the random values.

3.size: int or tuple of ints, optional: The shape of the array you want to create.

4.dtype: dtype, optional The type of the output you want.


In [208]:
# create a 1-D array
a = np.random.randint(low = 1, size = 5)
'''generates random integers between 0 (inclusive) and 1 (exclusive) 
which will always produce 0'''
a

array([0, 0, 0, 0, 0])

In [206]:
b=np.random.randint(low=1,high=6,size=(2,3))
'''
low=1: The smallest number in the array will be 1.
high=6:(exclusive) The largest number in the array will be 6-1 = 5.
size=(2, 3): The array will have 2 rows and 3 columns.'''
b

array([[3, 4, 1],
       [2, 4, 4]])

## concatenate

In [227]:
array2

array([[1, 2],
       [3, 4]])

In [229]:
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [231]:
np.concatenate([array2,ar2])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [233]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [235]:
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [237]:
np.concatenate([ar1,ar2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [243]:
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [241]:
#function returns a copy of the array collapsed into one dimension.
flatarr=array3d.flatten()
flatarr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [245]:
np.reshape(flatarr[:4],(2,2))

array([[1, 2],
       [3, 4]])

In [247]:
#create an identity matrix
#used to create a 2D array with ones on the diagonal and zeros elsewhere
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [249]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [251]:
#create a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(array2)
df

,0,1
0,1,2
1,3,4


In [253]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [257]:
np.info(np.concatenate)

concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.

    .. versionadded:: 1.20.0

Returns
-------
re